name: call_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  # Database
  intl: ^0.18.0
  objectbox: ^1.7.1
  flat_buffers: ^2.0.5
  objectbox_flutter_libs: any

  # Router
  go_router: ^6.0.1

  #misc
  worldtime: ^1.0.8
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  objectbox_generator: any

flutter:
  uses-material-design: true

  assets:
    - assets/contacts.json
